type Request @model {
  id: ID
  title: String
  dateCreated: String
  updateDueDate: String
  updatePaceInDays: String
  completionDueDate: String
  requestee: String
  privacy: String
  urgency: String
  requester: String
  includedUsers: [String]
  requestType: String
}

type GeneralRequest @model {
  id: ID
  requestID: ID
  description: String
}

type RequestUpdate @model {
  id: ID
  requestID: ID
  title: String
  message: String
  dateCreated: String
}